---
stages:
  - .pre
  - prepare
  - convert

pre-commit:
  image: docker.io/jfxs/pre-commit:latest
  stage: .pre
  script:
    - task --taskfile /lint.yml pre-commit DIR=$(pwd)

xlsx_conversion:
  image: python:3.13-bookworm
  stage: convert
  before_script:
    - apt update
    - apt install -y python3 python3-pip
    - pip3 install -r requirements.txt
    - cp "$AWS_CREDS" s3_tourism_credentials.json
  script:
    - python3 xlsx_to_csv.py

tsv_conversion:
  image: python:3.13-bookworm
  stage: convert
  before_script:
    - apt update
    - apt install -y python3 python3-pip
    - pip3 install -r requirements.txt
    - cp "$AWS_CREDS" s3_tourism_credentials.json
  script:
    - python3 tsv_to_s3.py
